import dayjs from 'dayjs/esm';
import { ICatalogs } from 'app/entities/catalogs/catalogs.model';

export interface IBatches {
  id: string;
  poName?: string | null;
  sequenceInPo?: number | null;
  scannerId?: string | null;
  previousProductionBatchId?: string | null;
  state?: string | null;
  inspectionSequence?: number | null;
  orderedQuantity?: number | null;
  producingQuantity?: number | null;
  totalProducingQuantity?: number | null;
  remainingQuantity?: number | null;
  totalremainingQuantity?: number | null;
  inspectedQuantity?: number | null;
  totalInspectedQuantity?: number | null;
  failedQuantity?: number | null;
  totalFailedQuantity?: number | null;
  colorId?: string | null;
  colorCode?: string | null;
  colorName?: string | null;
  colorBasematerial?: number | null;
  colorLabL?: number | null;
  colorLabA?: number | null;
  colorLabB?: number | null;
  colorA?: number | null;
  colorB?: number | null;
  colorC?: number | null;
  colorD?: number | null;
  colorE?: number | null;
  colorF?: number | null;
  colorG?: number | null;
  colorH?: number | null;
  colorI?: number | null;
  colorJ?: number | null;
  colorK?: number | null;
  colorL?: number | null;
  colorM?: number | null;
  colorN?: number | null;
  colorO?: number | null;
  colorP?: number | null;
  colorQ?: number | null;
  colorR?: number | null;
  colorS?: number | null;
  colorT?: number | null;
  colorU?: number | null;
  colorV?: number | null;
  colorW?: number | null;
  colorX?: number | null;
  colorY?: number | null;
  colorZ?: number | null;
  catalogId?: string | null;
  catalogExternalid?: string | null;
  catalogName?: string | null;
  catalogVersion?: string | null;
  catalogIsactive?: boolean | null;
  catalogCreatedtime?: dayjs.Dayjs | null;
  baseMaterialId?: number | null;
  orderedTime?: dayjs.Dayjs | null;
  startedTime?: dayjs.Dayjs | null;
  modifiedTime?: dayjs.Dayjs | null;
  suspendedTime?: dayjs.Dayjs | null;
  finishedTime?: dayjs.Dayjs | null;
  original?: string | null;
  colorCatalog?: Pick<ICatalogs, 'id'> | null;
}

export type NewBatches = Omit<IBatches, 'id'> & { id: null };
